version: 2

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: /root/hugo/public/
    steps:
      # checkout the repository
      - checkout:
          name: "Clone Github repository"
      - run: 
          name: "Download 3rd-party dependencies"
          command: |
            git submodule sync
            git submodule update --init
      - run: 
          name: "Build static pages with Hugo"
          command: | 
            # Link the public dir to the gh-pages branch
            rm -fr $HUGO_BUILD_DIR 
            git worktree add -B gh-pages $HUGO_BUILD_DIR origin/gh-pages 
            cd hugo
            HUGO_ENV=production hugo -v --buildFuture -d $HUGO_BUILD_DIR
      - run:
          name: "Test generated HTML"
          command: htmlproofer $HUGO_BUILD_DIR --url-swap "^\/${CIRCLE_PROJECT_REPONAME}:" --allow-hash-href --check-html --empty-alt-ignore
      - persist_to_workspace:
          root: public
          paths: .
  deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: public
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "oleg@kurapov.com"
            git config user.name "CircleCI Bot"
      - add_ssh_keys:
          fingerprints:
            - "8a:5d:e5:fb:69:58:1b:28:4e:d9:eb:ff:8d:7c:a6:3b"
      - run:
          name: Delete All SSH keys and Add the installed one
          command: ssh-add -D && ssh-add ~/.ssh/id_rsa_8a5de5fb69581b284ed9ebff8d7ca63b
      - run:
          name: Deploy the generated files to Github for publishing
          command: gh-pages --dotfiles --message "Automated publish to gh-pages [ci skip]" --dist public