version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    #environment:
      #HUGO_BUILD_DIR: ~/hugo/public/
    steps:
      - run: 
          name: "Install git" 
          command: apk update && apk add git
      # checkout the repository
      - checkout
      - run: 
          name: "Install git submodules for managing third-party dependencies"
          command: git submodule sync && git submodule update --init
      - run: 
          name: "Link the public dir to the gh-pages branch"
          command: rm -fr $HUGO_BUILD_DIR && git worktree add -B gh-pages $HUGO_BUILD_DIR origin/gh-pages
      - run: 
          name: "Build with Hugo"
          command: cd hugo && HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run:
          name: "Set some variables to add to the commit message"
          command: git config --global user.email "oleg@kurapov.com" && git config --global user.name "CircleCI Bot"
      - run: 
          name: "Push the generated files back to github"
          command: cd $HUGO_BUILD_DIR && git add --all && git commit -m "Automated publish to gh-pages [ci skip]" && git push