version: 2
jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: /root/hugo/public/
    steps:
      - run: 
          name: "Set up git" 
          command: |
            apk update && apk add git && 
            # Set some variables to add to the commit message
            git config --global user.email "oleg@kurapov.com" && git config --global user.name "CircleCI Bot"
      # checkout the repository
      - checkout:
          name: "Clone Github repository"
      - run: 
          name: "Set up build environment, download dependencies"
          command: git submodule sync && git submodule update --init
      - run: 
          name: "Build static pages with Hugo"
          command: | 
            # Link the public dir to the gh-pages branch
            rm -fr $HUGO_BUILD_DIR && git worktree add -B gh-pages $HUGO_BUILD_DIR origin/gh-pages && 
            cd hugo && HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run: 
          name: "Deploy the generated files to Github for publishing"
          command: cd $HUGO_BUILD_DIR && git add --all && git commit -m "Automated publish to gh-pages [ci skip]" && git push